server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_managementERP?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
jwt:
  secret: yourSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForSecurity
  expiration: 86400000
logging:
  level:
    org.springframework.web: DEBUG
    ma.formation.webService.rest: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
